Add an option `ignoreSurroundingSpaces` to allow to trim spaces between values
https://github.com/databricks/spark-xml/issues/236

It seems it is painful to treat these, especially, we provide a schema to XML file but it ended up with having some spaces. It ends up with an error such as ...

```
java.lang.NumberFormatException: For input string: "1 "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
```

It seems supporting to trim seems reasonable according to https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace

Author: hyukjinkwon <gurwls223@gmail.com>

Closes #237 from HyukjinKwon/ISSUE-236.

(cherry picked from commit d8eb3c1ffe1e428a6df2619d984b8a551c91b670)
Signed-off-by: hyukjinkwon <gurwls223@gmail.com>